# Cargo configuration for Debian 12 (libc 2.36-9+deb12u10) compatibility

[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=-Wl,--as-needed",
    "-C", "link-arg=-Wl,--no-undefined-version"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=-Wl,--as-needed",
    "-C", "link-arg=-Wl,--no-undefined-version"
]

# Ensure we use stable features only
[unstable]
# No unstable features to ensure compatibility

# Environment variables for consistent builds
[env]
RUSTC_BOOTSTRAP = "0"